global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX metrics
  - job_name: 'kafka'
    static_configs:
      - targets: 
        - 'kafka-1:9092'
        - 'kafka-2:9092'
        - 'kafka-3:9092'
    metrics_path: /metrics
    scrape_interval: 30s

  # Flink metrics
  - job_name: 'flink'
    static_configs:
      - targets: 
        - 'flink-taskmanager:9249'
    metrics_path: /metrics
    scrape_interval: 15s

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: /metrics
    scrape_interval: 30s

  # WebSocket server metrics
  - job_name: 'websocket-server'
    static_configs:
      - targets: ['websocket-server:8082']
    metrics_path: /metrics
    scrape_interval: 15s

  # Event simulator metrics
  - job_name: 'event-simulator'
    static_configs:
      - targets: ['event-simulator:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
